Description: >
    This is a template to deploy a new instance to use as a bastion

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    InstanceType:
        Description: Which instance type should we use to build the ECS cluster?
        Type: String
        Default: t2.micro

    KeyPair:
        Description: Name of the SSH KeyPair
        Type: String
        Default: 'test-keypair'

    VPC:
        Description: Choose which VPC this Bastion should be deployed to
        Type: AWS::EC2::VPC::Id

    Subnets:
        Description: Choose which subnets this Bastion should be deployed to
        Type: AWS::EC2::Subnet::Id

    SecurityGroups:
        Description: Select the Security Group to use for the Bastion
        Type: List<AWS::EC2::SecurityGroup::Id>
Mappings:

    # These are the latest ECS optimized AMIs as of August 2017:
    #
    #   amzn-ami-2017.03.f-amazon-ecs-optimized
    #   ECS agent:    1.14.4
    #   Docker:       17.03.2-ce
    #   ecs-init:     1.14.4-1
    #
    # You can find the latest available on this page of our documentation:
    # http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
    # (note the AMI identifier is region specific)

    AWSRegionToAMI:
        eu-west-3:
            AMI: ami-bd10a7c0
        eu-west-2:
            AMI: ami-acd5cdc8
        eu-west-1:
            AMI: ami-7827b301
        eu-central-1:
            AMI: ami-b378e8dc

Resources:

    Bastion:
        Type: AWS::EC2::Instance
        Properties:
            KeyName: !Ref KeyPair
            InstanceType: !Ref InstanceType
            SubnetId: !Ref Subnets
            SecurityGroupIds: !Ref SecurityGroups
            ImageId: ami-fe03b483
            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName}-Bastion